var annotated_dup =
[
    [ "AES_METHOD_REG_S", "structAES__METHOD__REG__S.html", "structAES__METHOD__REG__S" ],
    [ "cJSON", "structcJSON.html", "structcJSON" ],
    [ "cJSON_Hooks", "structcJSON__Hooks.html", "structcJSON__Hooks" ],
    [ "DEV_DESC_IF_S", "structDEV__DESC__IF__S.html", "structDEV__DESC__IF__S" ],
    [ "DP_BOOL_S", "structDP__BOOL__S.html", "structDP__BOOL__S" ],
    [ "DP_DESC_IF_S", "structDP__DESC__IF__S.html", "structDP__DESC__IF__S" ],
    [ "DP_PROP_BITMAP", "structDP__PROP__BITMAP.html", "structDP__PROP__BITMAP" ],
    [ "DP_PROP_ENUM_S", "structDP__PROP__ENUM__S.html", "structDP__PROP__ENUM__S" ],
    [ "DP_PROP_STR_S", "structDP__PROP__STR__S.html", "structDP__PROP__STR__S" ],
    [ "DP_PROP_VAL_S", "structDP__PROP__VAL__S.html", "structDP__PROP__VAL__S" ],
    [ "DP_PROP_VALUE_U", "unionDP__PROP__VALUE__U.html", "unionDP__PROP__VALUE__U" ],
    [ "FW_UG_S", "structFW__UG__S.html", "structFW__UG__S" ],
    [ "GW_ATTACH_ATTR_T", "structGW__ATTACH__ATTR__T.html", "structGW__ATTACH__ATTR__T" ],
    [ "GW_PROD_INFO_S", "structGW__PROD__INFO__S.html", "structGW__PROD__INFO__S" ],
    [ "MEM_PARTITION", "structMEM__PARTITION.html", "structMEM__PARTITION" ],
    [ "MEM_POOL_SETUP_TBL", "structMEM__POOL__SETUP__TBL.html", "structMEM__POOL__SETUP__TBL" ],
    [ "NW_IP_S", "structNW__IP__S.html", "structNW__IP__S" ],
    [ "NW_MAC_S", "structNW__MAC__S.html", "structNW__MAC__S" ],
    [ "POSIX_TM_S", "structPOSIX__TM__S.html", "structPOSIX__TM__S" ],
    [ "QUEUE_CLASS", "structQUEUE__CLASS.html", "structQUEUE__CLASS" ],
    [ "STAT_DP_VALUE_U", "unionSTAT__DP__VALUE__U.html", null ],
    [ "SUM_ZONE_S", "structSUM__ZONE__S.html", "structSUM__ZONE__S" ],
    [ "THRD_PARAM_S", "structTHRD__PARAM__S.html", "structTHRD__PARAM__S" ],
    [ "TUYA_STAT_DP_INFO_S", "structTUYA__STAT__DP__INFO__S.html", null ],
    [ "TY_DP_QUERY_S", "structTY__DP__QUERY__S.html", "structTY__DP__QUERY__S" ],
    [ "TY_IOT_CBS_S", "structTY__IOT__CBS__S.html", "structTY__IOT__CBS__S" ],
    [ "TY_IOT_GW_CBS_S", "structTY__IOT__GW__CBS__S.html", "structTY__IOT__GW__CBS__S" ],
    [ "TY_OBJ_DP_S", "structTY__OBJ__DP__S.html", "structTY__OBJ__DP__S" ],
    [ "TY_OBJ_DP_VALUE_U", "unionTY__OBJ__DP__VALUE__U.html", "unionTY__OBJ__DP__VALUE__U" ],
    [ "TY_RECV_OBJ_DP_S", "structTY__RECV__OBJ__DP__S.html", "structTY__RECV__OBJ__DP__S" ],
    [ "TY_RECV_RAW_DP_S", "structTY__RECV__RAW__DP__S.html", "structTY__RECV__RAW__DP__S" ]
];